version: '3.9'

services:
  mindflow:
    container_name: mindflow
    build: .
    image: mindflow-b
    env_file:
      - ./.env
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: mindflow-pg
    image: postgres:16.2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d mindflow -U root"]
      interval: 7s
      timeout: 10s
      retries: 7
      start_period: 10s
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mindflow
    # volumes:
    #   - ./docker-data/mindflow-pg:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"