version: '3'

tasks:
  docker-build:
    cmd: docker buildx build -t mindflow-b:latest --platform linux/amd64 .

  goimports:
    cmd: goimports -local "github.com/bogdanshibilov/mindflowbackend" -w ./internal ./cmd
  
  lint:
    cmd: golangci-lint run ./cmd/... ./internal/... --fix

  push-to-gar:
    cmds:
      - docker tag mindflow-b:latest europe-north1-docker.pkg.dev/mindflow-416115/mindflow-b/mindflow-b:latest
      - docker push europe-north1-docker.pkg.dev/mindflow-416115/mindflow-b/mindflow-b:latest

  migrate-up:
    cmd: go run ./cmd/migrator/main.go --conn-url=postgres://root:root@localhost:5432/mindflow --migrations-path="./migrations" --way=up
  
  migrate-down:
    cmd: go run ./cmd/migrator/main.go --conn-url=postgres://root:root@localhost:5432/mindflow --migrations-path="./migrations" --way=down